### ISSUE TITLE
Cross-Flashing IT firmware onto a SAS2108-based card doesn't seem to work

### ISSUE THREAD

**Issue by starcraft66** [marcan/lsirec#11]
I realize this procedure is completely untested but here I am reporting back from uncharted territory! I wanted to give it a shot on a pair of Supermicro-branded SAS2108 MEGARAID cards (Supermicro SMC2108) I acquired in some servers in attempt to use them without ordering replacement LSI 9211-8i cards from ebay.

Backing up the SBR, modifying it and writing it appears to work fine but when I try to hostboot the `2118it.bin` firmware, but the card didn't boot.

Here's the SBR I used:
```
Unk00 = 0x6132f561
Unk04 = 0xb34f30f5
Unk08 = 0x91c600f8
PCIVID = 0x1000
PCIPID = 0x0079
Unk10 = 0x0000
HwConfig = 0x0104
SubsysVID = 0x1000
SubsysPID = 0x9261
Unk18 = 0x00000000
Unk1c = 0x00000000
Unk20 = 0x00000000
Unk24 = 0x00000000
Unk28 = 0x00000000
Unk2c = 0x00000000
Unk30 = 0x00000000
Unk34 = 0x00000000
Unk38 = 0x00000000
Unk3c = 0x00000000
Interface = 0x00
Unk41 = 0x2c
Unk42 = 0x0000
Unk44 = 0x00000000
Unk48 = 0x0000
Unk4a = 0x00
SASAddr = 0x5003048011005000
```

When trying to hostboot `2118it.bin`:
```
root@kali:~/Desktop/lsirec# ./lsirec 0000:04:00.0 hostboot 2118it.bin
Device in MEGARAID mode
Resetting adapter in HCB mode...
Trying unlock in MPT mode...
Trying unlock in MEGARAID mode...
Device in MEGARAID mode
IOC is RESET
Setting up HCB...
HCDW virtual: 0x7fcf4de00000
HCDW physical: 0x43e200000
Loading firmware...
Loaded 696048 bytes
Booting IOC...
IOC is RESET
IOC failed to become ready
```

I'm guessing I can't just boot SAS2008 firmware on a SAS2108 chipset or something? As far as I know, SAS2108 cards don't seem to actually have IT firmware (based on a quick google search, correct me if I'm wrong) which is why I tried the SAS2008 firmware.

Is there something I'm overlooking or is the crossflash operation I'm trying to achieve impossible?

**Comment by wodianw** [comment]
Hi,
looks like sas2108 card can not flash to 2008 IT.i try flash 2008 smc/sbr in M5015 and can not work.
i can't find any information on google,maybe can't do it

**Comment by starcraft66** [comment]
Yeah, I kinda misread the readme in this tool. It works great on SAS2108 cards to recover them, but you can't flash SAS2008 IT firmware on them :man_facepalming:. I ended up buying SAS2008-based cards and cross-flashing them with this tool later, worked like a charm :)
