### ISSUE TITLE
open bar1: No such file or directory

### ISSUE THREAD

**Issue by nkthupili1** [marcan/lsirec#4]
I'm getting the following  error using the lsirec on 9400-8i.  Controller has valid FW & bios. Both lsiutil &StorCli can see/query the device fine.  

I'm on Centos 7.6 and compiled both utils. lsirec needed -std=gnu99
for successful build as noted in the issue#2

# lspci -s 0000:01:00.0
01:00.0 Serial Attached SCSI controller: LSI Logic / Symbios Logic SAS3408 Fusion-MPT Tri-Mode I/O Controller Chip (IOC) (rev 01)

# lsirec 0000:01:00.0 rescan
open bar1: No such file or directory

#lsirec 0000:01:00.0 info
open bar1: No such file or directory

# lsirec 0000:01:00.0 reset
open bar1: No such file or directory

`
# storcli show
CLI Version = 007.0709.0000.0000 Aug 14, 2018
Operating system = Linux 3.10.0-957.5.1.el7.x86_64
Status Code = 0
Status = Success
Description = None

Number of Controllers = 1
Host Name = hp8300-centos.localdomain
Operating System  = Linux 3.10.0-957.5.1.el7.x86_64
StoreLib IT Version = 07.0705.0200.0000
StoreLib IR3 Version = 16.02-0

IT System Overview :
==================

--------------------------------------------------------------------------
Ctl Model       AdapterType   VendId DevId SubVendId SubDevId PCI Address 
--------------------------------------------------------------------------
  0 HBA 9400-8i   SAS3408(B0) 0x1000  0xAF    0x1000   0x3010 00:01:00:00 

`
$lsiutil -e
<snip>
Main menu, select an option:  [1-99 or e/p/w or 0 to quit] 1

Current active firmware version is 0a000000 (10.00.00)
Firmware image's version is BL 10:29:14     01/21/2019
  Ventura Boot Loader Vendor  Str
  SCGCQ02030034
x86 BIOS image's version is MPT35BIOS-9.19.00.00 (2018.12.24)
EFI BIOS image's version is 0.10.00.00

**Comment by marcan** [comment]
lsirec is for SAS2x08 (particularly SAS2008) controllers, while yours is a SAS3408. I don't have one of those and I have no idea if they could be easily supported, sorry.
