### ISSUE TITLE
Mfg data checksum error

### ISSUE THREAD

**Issue by BurningTheSky** [marcan/lsirec#8]
I'm not the biggest Linux/CentOS user so please bear with me...
I cloned and did a make on the files here, I unbound then halted the card, extracted the SBR and now I'm running into issues. When I parsed the SBR to a CFG file everything is pretty much zeroed out except the address which is all F's, any ideas what I have done wrong or what I am missing?

> 
> [root@CentOS lsirec]$ lspci -Dmmnn|grep LSI
> 0000:02:00.0 "SCSI storage controller [0100]" "LSI Logic / Symbios Logic [1000]" "SAS2008 PCI-Express Fusion-MPT SAS-2 [Falcon] [0072]" -r03 "LSI Logic / Symbios Logic [1000]" "SAS2008 PCI-Express Fusion-MPT SAS-2 [Falcon] [0072]"
> [root@CentOS lsirec]# ./lsirec 0000:02:00.0 unbind
> Trying unlock in MPT mode...
> Device in MPT mode
> [root@CentOS lsirec]# ./lsirec 0000:02:00.0 halt
> Device in MPT mode
> Resetting adapter in HCB mode...
> Trying unlock in MPT mode...
> Device in MPT mode
> IOC is RESET 
> [root@CentOS lsirec]# ./lsirec 0000:02:00.0 readsbr H200.SBR
> Device in MPT mode
> Using I2C address 0x54
> Using EEPROM type 1
> Reading SBR...
> SBR saved to H200.SBR
> [root@CentOS lsirec]# python3 sbrtool.py parse H200.SBR H200.CFG
> WARNING: Mfg data checksum error
> WARNING: SAS address checksum error
> [root@CentOS lsirec]# cat H200.CFG 
> Unk00 = 0x00000000
> Unk04 = 0x00000000
> Unk08 = 0x00000000
> PCIVID = 0x0000
> PCIPID = 0x0000
> Unk10 = 0x0000
> HwConfig = 0x0000
> SubsysVID = 0x0000
> SubsysPID = 0x0000
> Unk18 = 0x00000000
> Unk1c = 0x00000000
> Unk20 = 0x00000000
> Unk24 = 0x00000000
> Unk28 = 0x00000000
> Unk2c = 0x00000000
> Unk30 = 0x00000000
> Unk34 = 0x00000000
> Unk38 = 0x00000000
> Unk3c = 0x00000000
> Interface = 0x00
> Unk41 = 0x00
> Unk42 = 0x0000
> Unk44 = 0x00000000
> Unk48 = 0x0000
> Unk4a = 0x00
> SASAddr = 0xffffffffffffffff

**Comment by ezonakiusagi** [comment]
you're seeing the checksum error because your entire SBR content is zero'd out and you have 0xFF for your SAS address section, which isn't needed by the way for the LSI or Dell firmwares.

is this a card that you previously wrote the empty SBR on to?

**Comment by BurningTheSky** [comment]
The only thing I've done was follow various guides to flash to IT mode. Shall I just write a copy of the Dell H200 SBR onto it? Or should I do something else?

**Comment by marcan** [comment]
A lot of guides out there have you wipe the SBR because they don't know any better.

If you have an H200 you should use that SBR. For other cards probably the sas9211-8i_itir.cfg sample is a closer config. Change any settings you want changed, build them with sbrtool, and flash them.

Of course, if the card is otherwise working fine, you can also choose not to care and just leave the SBR blank, which means it will use default settings for everything. But it's not really a state that any "normal" card should be in, it's just something a lot of guides have latched on to because it happens to work for flashing to IT mode.

**Comment by BurningTheSky** [comment]
Right, that makes sense. It does sound like that's what the guide suggested. Thanks for the advice, I have copied the H200 SBR and removed the SAS address, I booted into unraid and it could see a single disk with smart data so I think it's all working now! Thanks!
